version: '3'

services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: iluvcoffee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  test-db:
    image: postgres:13
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: iluvcoffee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4:5
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - '8080:80'
